### ISSUE TITLE
when I use the receiver I got an error :  undefined reference to `mq_open'; env docker golang:1.13-stretch container

### ISSUE THREAD

**Issue by newgoo** [syucream/posix_mq#1]
# gitlab.kucoin.net/goblin/bhex-market/vendor/github.com/syucream/posix_mq/src/posix_mq
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_C2func_mq_close':
/tmp/go-build/cgo-gcc-prolog:56: undefined reference to `mq_close'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_C2func_mq_notify':
/tmp/go-build/cgo-gcc-prolog:81: undefined reference to `mq_notify'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_C2func_mq_receive':
/tmp/go-build/cgo-gcc-prolog:133: undefined reference to `mq_receive'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_C2func_mq_send':
/tmp/go-build/cgo-gcc-prolog:161: undefined reference to `mq_send'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_C2func_mq_unlink':
/tmp/go-build/cgo-gcc-prolog:184: undefined reference to `mq_unlink'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_Cfunc_mq_close':
/tmp/go-build/cgo-gcc-prolog:218: undefined reference to `mq_close'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_Cfunc_mq_notify':
/tmp/go-build/cgo-gcc-prolog:239: undefined reference to `mq_notify'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_Cfunc_mq_receive':
/tmp/go-build/cgo-gcc-prolog:283: undefined reference to `mq_receive'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_Cfunc_mq_send':
/tmp/go-build/cgo-gcc-prolog:307: undefined reference to `mq_send'
/tmp/go-build634599583/b031/_x002.o: In function `_cgo_8c0fc01079fd_Cfunc_mq_unlink':
/tmp/go-build/cgo-gcc-prolog:326: undefined reference to `mq_unlink'
/tmp/go-build634599583/b031/_x002.o: In function `mq_open4':
../../vendor/github.com/syucream/posix_mq/src/posix_mq/wrapper.go:11: undefined reference to `mq_open'
collect2: error: ld returned 1 exit status

**Comment by diegosundevil** [comment]
I have the same problem...

> $ go build github.com/syucream/posix_mq/example/exec
> # github.com/syucream/posix_mq/src/posix_mq
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_close':
> /tmp/go-build/cgo-gcc-prolog:56: undefined reference to `mq_close'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_notify':
> /tmp/go-build/cgo-gcc-prolog:81: undefined reference to `mq_notify'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_receive':
> /tmp/go-build/cgo-gcc-prolog:133: undefined reference to `mq_receive'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_send':
> /tmp/go-build/cgo-gcc-prolog:161: undefined reference to `mq_send'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_unlink':
> /tmp/go-build/cgo-gcc-prolog:184: undefined reference to `mq_unlink'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_close':
> /tmp/go-build/cgo-gcc-prolog:218: undefined reference to `mq_close'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_notify':
> /tmp/go-build/cgo-gcc-prolog:239: undefined reference to `mq_notify'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_receive':
> /tmp/go-build/cgo-gcc-prolog:283: undefined reference to `mq_receive'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_send':
> /tmp/go-build/cgo-gcc-prolog:307: undefined reference to `mq_send'
> /tmp/go-build423049335/b031/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_unlink':
> /tmp/go-build/cgo-gcc-prolog:326: undefined reference to `mq_unlink'
> /tmp/go-build423049335/b031/_x002.o: In function `mq_open':
> /usr/include/x86_64-linux-gnu/bits/mqueue2.h:56: undefined reference to `mq_open'
> collect2: error: ld returned 1 exit status
>

**Comment by diegosundevil** [comment]
I have the same problem...

```
$ go build github.com/syucream/posix_mq/src/posix_mq
# github.com/syucream/posix_mq/src/posix_mq
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_close':
/tmp/go-build/cgo-gcc-prolog:56: undefined reference to `mq_close'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_notify':
/tmp/go-build/cgo-gcc-prolog:81: undefined reference to `mq_notify'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_receive':
/tmp/go-build/cgo-gcc-prolog:133: undefined reference to `mq_receive'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_send':
/tmp/go-build/cgo-gcc-prolog:161: undefined reference to `mq_send'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_C2func_mq_unlink':
/tmp/go-build/cgo-gcc-prolog:184: undefined reference to `mq_unlink'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_close':
/tmp/go-build/cgo-gcc-prolog:218: undefined reference to `mq_close'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_notify':
/tmp/go-build/cgo-gcc-prolog:239: undefined reference to `mq_notify'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_receive':
/tmp/go-build/cgo-gcc-prolog:283: undefined reference to `mq_receive'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_send':
/tmp/go-build/cgo-gcc-prolog:307: undefined reference to `mq_send'
/tmp/go-build056816785/b001/_x002.o: In function `_cgo_028fcf2c52df_Cfunc_mq_unlink':
/tmp/go-build/cgo-gcc-prolog:326: undefined reference to `mq_unlink'
/tmp/go-build056816785/b001/_x002.o: In function `mq_open':
/usr/include/x86_64-linux-gnu/bits/mqueue2.h:56: undefined reference to `mq_open'
collect2: error: ld returned 1 exit status

```

**Comment by syucream** [comment]
Thanks for your report, will check that 👀

**Comment by syucream** [comment]
https://github.com/syucream/posix_mq/pull/2 should fix this issue. Try fixed version. It works well, like below:
```
$ make docker
...
Successfully tagged posix_mq_stretch:latest
...
$ docker run -it posix_mq_stretch ./sender
Sent a new message
Sent a new message
Sent a new message
Sent a new message
Sent a new message
Sent a new message
Sent a new message
...
```
